/**
 * Embedded app-tables migration — the runtime source of truth. The release
 * ships a bundled server, so the dev-time drizzle-kit output under
 * `packages/db/drizzle/` is unreadable in production; only these embedded TS
 * statements run at runtime.
 *
 * Provenance: generated by `pnpm --filter @workspace-welcome/db db:generate`
 * (drizzle-kit 0.31.10, dialect "turso") on 2026-09-14 from
 * `drizzle/0000_foamy_beyonder.sql`. The generated `CREATE TABLE app_meta`
 * statement is deliberately omitted here: `migrate.ts` bootstraps `app_meta`
 * with an idempotent CREATE TABLE IF NOT EXISTS (identical DDL) before any
 * migration runs, because the runner needs that table to record
 * `schema_version`.
 */
export const migration0001 = {
  id: "0001_app_tables",
  statements: [
    `CREATE TABLE \`project_configs\` (
	\`path\` text PRIMARY KEY NOT NULL,
	\`artifact_dirs_json\` text NOT NULL
);`,
    `CREATE TABLE \`project_overrides\` (
	\`path\` text PRIMARY KEY NOT NULL,
	\`pinned\` integer NOT NULL,
	\`note\` text NOT NULL,
	\`last_opened_at\` text,
	\`hidden\` integer NOT NULL
);`,
    `CREATE TABLE \`roots\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`path\` text NOT NULL,
	\`label\` text NOT NULL,
	\`added_at\` text NOT NULL
);`,
    `CREATE UNIQUE INDEX \`roots_path_unique\` ON \`roots\` (\`path\`);`,
    `CREATE TABLE \`settings\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`editor_command\` text NOT NULL,
	\`terminal_command\` text,
	\`snitch_path\` text,
	\`exclude_globs_json\` text NOT NULL,
	\`ideation_json\` text NOT NULL,
	CONSTRAINT "settings_singleton" CHECK("settings"."id" = 1)
);`,
  ],
} as const;
