/**
 * Embedded user-feed table migration — the runtime source of truth (see
 * ./0001_app_tables.ts for why SQL is embedded rather than read from
 * packages/db/drizzle/ at runtime).
 *
 * Provenance: generated by `pnpm --filter @workspace-welcome/db db:generate`
 * (drizzle-kit 0.31.10, dialect "turso") on 2026-09-14, emitted as
 * `drizzle/0002_swift_fabian_cortez.sql` (drizzle-kit journal numbering is
 * one behind the embedded runtime ids: journal 0002 == embedded 0003, so
 * this file embeds as 0003). Statements are verbatim from the generated
 * file. No FK to forge_repos is intentional — see schema.ts's forgeFeedItems
 * comment (the feed spans repos no workspace project maps to).
 */
export const migration0003 = {
  id: "0003_feed",
  statements: [
    `CREATE TABLE \`forge_feed_items\` (
	\`kind\` text NOT NULL,
	\`repo_slug\` text NOT NULL,
	\`number\` integer NOT NULL,
	\`title\` text NOT NULL,
	\`url\` text NOT NULL,
	\`updated_at\` text,
	\`labels_json\` text NOT NULL,
	\`is_draft\` integer DEFAULT false NOT NULL,
	PRIMARY KEY(\`kind\`, \`repo_slug\`, \`number\`)
);`,
  ],
} as const;
