/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsConceptsRouteImport } from './routes/docs/concepts'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsSettingsRouteImport } from './routes/docs/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsConceptsRoute = DocsConceptsRouteImport.update({
  id: '/docs/concepts',
  path: '/docs/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/docs/getting-started',
  path: '/docs/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSettingsRoute = DocsSettingsRouteImport.update({
  id: '/docs/settings',
  path: '/docs/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/features': typeof FeaturesRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/settings': typeof DocsSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/features': typeof FeaturesRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/settings': typeof DocsSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/features': typeof FeaturesRoute
  '/docs/concepts': typeof DocsConceptsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/settings': typeof DocsSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/features'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/features'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/settings'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/features'
    | '/docs/concepts'
    | '/docs/getting-started'
    | '/docs/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  FeaturesRoute: typeof FeaturesRoute
  DocsConceptsRoute: typeof DocsConceptsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsSettingsRoute: typeof DocsSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/concepts': {
      id: '/docs/concepts'
      path: '/docs/concepts'
      fullPath: '/docs/concepts'
      preLoaderRoute: typeof DocsConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/docs/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/settings': {
      id: '/docs/settings'
      path: '/docs/settings'
      fullPath: '/docs/settings'
      preLoaderRoute: typeof DocsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  FeaturesRoute: FeaturesRoute,
  DocsConceptsRoute: DocsConceptsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsSettingsRoute: DocsSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
