/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91__labChar93RouteImport } from './routes/[__lab]'
import { Route as PartsPreviewRouteImport } from './routes/parts-preview'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectSplatRouteImport } from './routes/project.$'
import { Route as ProjectsSplatRouteImport } from './routes/projects.$'
import { Route as ReportsKeyRouteImport } from './routes/reports/$key'
import { Route as ApiArtifactsViewRouteImport } from './routes/api/artifacts/view'
import { Route as ApiFilesDownloadRouteImport } from './routes/api/files/download'
import { Route as ApiFilesViewRouteImport } from './routes/api/files/view'
import { Route as ApiIdeationChatRouteImport } from './routes/api/ideation/chat'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__labChar93Route = Char91__labChar93RouteImport.update({
  id: '/__lab',
  path: '/__lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsPreviewRoute = PartsPreviewRouteImport.update({
  id: '/parts-preview',
  path: '/parts-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSplatRoute = ProjectSplatRouteImport.update({
  id: '/project/$',
  path: '/project/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSplatRoute = ProjectsSplatRouteImport.update({
  id: '/projects/$',
  path: '/projects/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsKeyRoute = ReportsKeyRouteImport.update({
  id: '/reports/$key',
  path: '/reports/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsViewRoute = ApiArtifactsViewRouteImport.update({
  id: '/api/artifacts/view',
  path: '/api/artifacts/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDownloadRoute = ApiFilesDownloadRouteImport.update({
  id: '/api/files/download',
  path: '/api/files/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesViewRoute = ApiFilesViewRouteImport.update({
  id: '/api/files/view',
  path: '/api/files/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdeationChatRoute = ApiIdeationChatRouteImport.update({
  id: '/api/ideation/chat',
  path: '/api/ideation/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/__lab': typeof Char91__labChar93Route
  '/parts-preview': typeof PartsPreviewRoute
  '/settings': typeof SettingsRoute
  '/project/$': typeof ProjectSplatRoute
  '/projects/$': typeof ProjectsSplatRoute
  '/reports/$key': typeof ReportsKeyRoute
  '/api/artifacts/view': typeof ApiArtifactsViewRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/view': typeof ApiFilesViewRoute
  '/api/ideation/chat': typeof ApiIdeationChatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/__lab': typeof Char91__labChar93Route
  '/parts-preview': typeof PartsPreviewRoute
  '/settings': typeof SettingsRoute
  '/project/$': typeof ProjectSplatRoute
  '/projects/$': typeof ProjectsSplatRoute
  '/reports/$key': typeof ReportsKeyRoute
  '/api/artifacts/view': typeof ApiArtifactsViewRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/view': typeof ApiFilesViewRoute
  '/api/ideation/chat': typeof ApiIdeationChatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__lab': typeof Char91__labChar93Route
  '/parts-preview': typeof PartsPreviewRoute
  '/settings': typeof SettingsRoute
  '/project/$': typeof ProjectSplatRoute
  '/projects/$': typeof ProjectsSplatRoute
  '/reports/$key': typeof ReportsKeyRoute
  '/api/artifacts/view': typeof ApiArtifactsViewRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/view': typeof ApiFilesViewRoute
  '/api/ideation/chat': typeof ApiIdeationChatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/__lab'
    | '/parts-preview'
    | '/settings'
    | '/project/$'
    | '/projects/$'
    | '/reports/$key'
    | '/api/artifacts/view'
    | '/api/files/download'
    | '/api/files/view'
    | '/api/ideation/chat'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/__lab'
    | '/parts-preview'
    | '/settings'
    | '/project/$'
    | '/projects/$'
    | '/reports/$key'
    | '/api/artifacts/view'
    | '/api/files/download'
    | '/api/files/view'
    | '/api/ideation/chat'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/__lab'
    | '/parts-preview'
    | '/settings'
    | '/project/$'
    | '/projects/$'
    | '/reports/$key'
    | '/api/artifacts/view'
    | '/api/files/download'
    | '/api/files/view'
    | '/api/ideation/chat'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91__labChar93Route: typeof Char91__labChar93Route
  PartsPreviewRoute: typeof PartsPreviewRoute
  SettingsRoute: typeof SettingsRoute
  ProjectSplatRoute: typeof ProjectSplatRoute
  ProjectsSplatRoute: typeof ProjectsSplatRoute
  ReportsKeyRoute: typeof ReportsKeyRoute
  ApiArtifactsViewRoute: typeof ApiArtifactsViewRoute
  ApiFilesDownloadRoute: typeof ApiFilesDownloadRoute
  ApiFilesViewRoute: typeof ApiFilesViewRoute
  ApiIdeationChatRoute: typeof ApiIdeationChatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__lab': {
      id: '/__lab'
      path: '/__lab'
      fullPath: '/__lab'
      preLoaderRoute: typeof Char91__labChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts-preview': {
      id: '/parts-preview'
      path: '/parts-preview'
      fullPath: '/parts-preview'
      preLoaderRoute: typeof PartsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$': {
      id: '/project/$'
      path: '/project/$'
      fullPath: '/project/$'
      preLoaderRoute: typeof ProjectSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$': {
      id: '/projects/$'
      path: '/projects/$'
      fullPath: '/projects/$'
      preLoaderRoute: typeof ProjectsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$key': {
      id: '/reports/$key'
      path: '/reports/$key'
      fullPath: '/reports/$key'
      preLoaderRoute: typeof ReportsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts/view': {
      id: '/api/artifacts/view'
      path: '/api/artifacts/view'
      fullPath: '/api/artifacts/view'
      preLoaderRoute: typeof ApiArtifactsViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/download': {
      id: '/api/files/download'
      path: '/api/files/download'
      fullPath: '/api/files/download'
      preLoaderRoute: typeof ApiFilesDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/view': {
      id: '/api/files/view'
      path: '/api/files/view'
      fullPath: '/api/files/view'
      preLoaderRoute: typeof ApiFilesViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ideation/chat': {
      id: '/api/ideation/chat'
      path: '/api/ideation/chat'
      fullPath: '/api/ideation/chat'
      preLoaderRoute: typeof ApiIdeationChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91__labChar93Route: Char91__labChar93Route,
  PartsPreviewRoute: PartsPreviewRoute,
  SettingsRoute: SettingsRoute,
  ProjectSplatRoute: ProjectSplatRoute,
  ProjectsSplatRoute: ProjectsSplatRoute,
  ReportsKeyRoute: ReportsKeyRoute,
  ApiArtifactsViewRoute: ApiArtifactsViewRoute,
  ApiFilesDownloadRoute: ApiFilesDownloadRoute,
  ApiFilesViewRoute: ApiFilesViewRoute,
  ApiIdeationChatRoute: ApiIdeationChatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
