import type { GitHost, RemoteInfo } from "./types";

/**
 * Generate a bash script that clones the given projects into the current
 * working directory, forcing SSH URLs.
 *
 * Pure function — no I/O, no server state. The caller passes the projects it
 * selected from the dashboard; this returns the script text.
 *
 * Design:
 *   - Clones into $PWD (no target path beyond the repo's own basename), so the
 *     script is portable across machines and doesn't hardcode any path.
 *   - Every cloneable URL is rewritten to SSH form via the parsed remote
 *     (host + slug). Repos whose host we can't classify fall back to their
 *     original URL with a comment so the user notices before running it.
 *   - Idempotent: skips a repo if its target directory already exists, so
 *     re-running the script doesn't clobber half-pulled clones.
 *   - Dedupes by slug — the same repo tracked under two local roots only
 *     clones once.
 */

/** Hosts we can confidently rewrite to `git@<canonical-host>/<slug>.git`. */
const SSH_HOST: Record<GitHost, string | null> = {
  github: "github.com",
  gitlab: "gitlab.com",
  bitbucket: "bitbucket.org",
  codeberg: "codeberg.org",
  sourcehut: "git.sr.ht",
  other: null,
};

/** The clone target directory name for a slug: the repo segment. */
function dirNameFor(slug: string): string {
  const parts = slug.split("/");
  return parts[parts.length - 1] ?? slug;
}

/**
 * One clone target, after rewriting + dedupe.
 * `note` is non-empty when we couldn't force SSH (surfaced as a comment).
 */
interface CloneLine {
  dir: string;
  url: string;
  note: string;
}

/** Rewrite a parsed remote into a force-SSH clone line (or a fallback). */
function toCloneLine(remote: RemoteInfo): CloneLine {
  const canonical = SSH_HOST[remote.host];
  if (canonical) {
    return {
      dir: dirNameFor(remote.slug ?? remote.url),
      url: `git@${canonical}:${remote.slug}.git`,
      note: "",
    };
  }
  // Unclassifiable host (rare self-hosted): keep the original URL and flag it
  // so the user can adjust before running.
  return {
    dir: dirNameFor(remote.slug ?? remote.url),
    url: remote.url,
    note: "could not force SSH — using original URL",
  };
}

/** Minimal shape buildCloneScript needs — keeps the picker's input decoupled. */
export interface CloneableProject {
  name: string;
  remote: RemoteInfo | null;
}

/**
 * Build the clone script for a set of projects.
 * Projects without a parseable remote are silently dropped (nothing to clone).
 */
export function buildCloneScript(projects: CloneableProject[]): string {
  // Rewrite + dedupe by directory name. Two distinct repos could share a
  // basename (e.g. github.com:a/x and github.com:b/x); we keep the first
  // occurrence and note the collision on the second so the user sees it
  // rather than silently skipping.
  const byDir = new Map<string, CloneLine>();
  for (const p of projects) {
    if (!p.remote) continue;
    const line = toCloneLine(p.remote);
    const existing = byDir.get(line.dir);
    if (existing) {
      if (existing.url !== line.url) {
        existing.note = `directory "${line.dir}" already used by ${existing.url}; skipping ${p.name}`;
      }
      continue;
    }
    byDir.set(line.dir, line);
  }

  const lines = [...byDir.values()];
  const total = lines.length;
  const date = new Date().toISOString().slice(0, 10);

  const out: string[] = [];
  out.push("#!/usr/bin/env bash");
  out.push("# Bootstrap clone script — generated by Workspace Welcome.");
  out.push(`# ${total} repo${total === 1 ? "" : "s"} · ${date} · forces SSH.`);
  out.push("# Clones each repo into the current directory. Re-runnable: skips");
  out.push("# anything that's already there so partial runs are safe.");
  out.push("set -euo pipefail");
  out.push("");
  out.push('cloned=0; skipped=0');
  out.push("");

  for (const line of lines) {
    if (line.note) {
      out.push(`# ${line.note}`);
    }
    out.push(`if [ -d "${line.dir}" ]; then`);
    out.push(`  echo "skip   ${line.dir} (already exists)"`);
    out.push(`  skipped=$((skipped + 1))`);
    out.push(`else`);
    out.push(`  echo "clone  ${line.dir}"`);
    out.push(`  git clone "${line.url}"`);
    out.push(`  cloned=$((cloned + 1))`);
    out.push(`fi`);
    out.push("");
  }

  out.push('echo "---"');
  out.push('echo "done: $cloned cloned, $skipped skipped"');
  out.push("");

  return out.join("\n");
}
